[package]
name = "hyperion-nmparser"
version = "0.1.0"
edition = "2024"

[dependencies]
# R Integration (needed for extendr macros in modules)
extendr-api = { workspace = true }
hyperion-core = { path = "../core" }

# Pharos components
nmparser = {workspace = true}
config = { workspace = true }

# Core utilities
fs-err = { workspace = true }
