---
title: "grd"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{grd}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

vignette_root <- tempfile("hyperion-vignette-")
dir.create(vignette_root, recursive = TRUE)
file.copy(
  list.files(system.file("extdata", package = "hyperion"), full.names = TRUE),
  vignette_root,
  recursive = TRUE
)
file.copy(
  system.file("pharos.toml", package = "hyperion"),
  vignette_root
)
knitr::opts_knit$set(root.dir = vignette_root)
```

```{r setup}
library(hyperion)
library(dplyr)
```

```{r}
get_gradients(file.path("grd", "bql.grd"))  |> 
  slice_tail(n = 1) |> 
  summarize(any_zero = any(across(everything(), ~ .x == 0))) |> 
  pull(any_zero) |> 
  as.numeric()
```

```{r}
get_gradients(file.path("models", "onecmt", "run001"))

get_gradients(file.path("models", "onecmt", "run001"))

get_gradients(file.path("models", "onecmt", "run001", "run001.grd"))
```


```{r}
get_gradients(file.path("models", "onecmt", "run002"))

get_gradients(file.path("models", "onecmt", "run002.mod"))

get_gradients(file.path("models", "onecmt", "run002", "run002.grd"))

get_gradients(file.path("models", "onecmt", "run002_metadata.json"))
```
