---
title: "lst"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{lst}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

vignette_root <- tempfile("hyperion-vignette-")
dir.create(vignette_root, recursive = TRUE)
file.copy(
  list.files(system.file("extdata", package = "hyperion"), full.names = TRUE),
  vignette_root,
  recursive = TRUE
)
file.copy(
  system.file("pharos.toml", package = "hyperion"),
  vignette_root
)
knitr::opts_knit$set(root.dir = vignette_root)
```

```{r setup}
library(hyperion)
```

# Parse lst
```{r}
get_run_info(
	read_model(	
		file.path("models", "onecmt", "run001.mod")
	)
)
```

```{r}
get_run_info(
	read_model(	
		file.path("models", "onecmt", "run003b1.mod")
	)
)
```

```{r}
mod_sum <- summary(
	read_model(
		file.path("models", "onecmt", "run002.mod")
	)
)

mod_sum
```
```{r}
mod_sum <- summary(
	read_model(
		file.path("models", "onecmt", "run003b1.mod")
	)
)

mod_sum
```





