# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib hyperion, .registration = TRUE
NULL

#' Initializes pharos
#'
#' @param config_path path to where pharos.toml is saved (should be colocated to where pharos is
#' run from)
#'
#' @return nothing
#' @export
#'
#' @examples \dontrun{
#' init("model/nonmem/submission-log/pharos.toml")
#' }
init <- function(config_path) .Call(wrap__init, config_path)

silence_panic_output <- function() .Call(wrap__silence_panic_output)

find_pharos_config_file <- function() .Call(wrap__find_pharos_config_file)

#' Read a NONMEM model from a .mod or .ctl file
#'
#' @param path path to a .mod or .ctl file.
#'
#' @return A `hyperion_nonmem_model` S3 object with attributes:
#'   - `filename`: the model stem (e.g. `"run001"`)
#'   - `model_source`: path to the source file, relative to the pharos config dir
#'   - `run_status`: `"run"`, `"running"`, or `"not_run"` determined from output files on disk
#' @export
#'
#' @examples \dontrun{
#' read_model("model/nonmem/run001.mod")
#' }
read_model <- function(path) .Call(wrap__read_model, path)

#' Read a model from an .lst file (internal)
#'
#' @param path path to an .lst file, model output directory, or metadata.json file.
#'
#' @return A `hyperion_nonmem_model` S3 object with attributes:
#'   - `filename`: the model stem (e.g. `"run001"`)
#'   - `model_source`: path to the source file, relative to the pharos config dir
#'   - `run_status`: `"run"`, `"running"`, or `"not_run"` determined from output files on disk
#' @keywords internal
read_model_from_lst <- function(path) .Call(wrap__read_model_from_lst, path)

#' Copies model file to new model file
#'
#' @param from path to model file to copy or hyperion_nonmem_model object
#' @param to path to model file to write to
#' @param overwrite boolean, wheter to overwrite existing model. Default FALSE
#' @param ext_file path to ext file to use for parameter estimates
#' @param update character or character vector specifying which parameters to update from ext file.
#' Options: "all", "none", "theta", "omega", "sigma". Examples: "all" or c("theta", "omega")
#' @param jitter Single numeric value for parameter jittering using a uniform
#' distribution. Each parameter value is multiplied by a random factor between
#' (1 - jitter%) and (1 + jitter%) with boundary enforcement.
#' @param jitter_excluded character or character vector of parameter names to exclude from jittering.
#' Examples: "THETA1" or c("THETA1")
#' @param seed integer for random number generator seed to ensure reproducible jittering
#' @param description Description of model in metadata file
#' @param based_on Character vector of model names/paths that this model is based on
#' @param tags Character vector of tags to attach to the model in metadata
#' @param no_metadata boolean, if true, does not create metadatafile, default FALSE
#'
#' @return path to new model file (invisible) todo
#' @export
#'
#' @examples \dontrun{
#' copy_model(from = "model/nonmem/run001.mod", to = "model/nonmem/run002.mod")
#' }
copy_model <- function(from, to, overwrite = FALSE, ext_file = NULL, update = 'none', jitter = NULL, jitter_excluded = NULL, seed = NULL, description, based_on = NULL, tags = NULL, no_metadata = FALSE) .Call(wrap__copy_model_wrap, from, to, overwrite, ext_file, update, jitter, jitter_excluded, seed, description, based_on, tags, no_metadata)

#' Gets model run summary (internal implementation)
#'
#' @param directory path to model run output directory containing .ext, .lst files,
#' or a hyperion_nonmem_model object
#' @param hide_off_diagonal_params boolean, if TRUE will not display the unfixed off-diagonal
#' estimated parameters
#'
#' @return hyperion_nonmem_summary S3 object
#' @keywords internal
get_model_summary <- function(directory, hide_off_diagonal_params = FALSE) .Call(wrap__get_model_summary, directory, hide_off_diagonal_params)

#' Parses lst file for run details and heuristics
#'
#' @param path path to model file, model output directory, lst file or metadata json file,
#' or a hyperion_nonmem_model object
#'
#' @return list of data.frames of run details and run heuristics
#' @export
#'
#' @examples \dontrun{
#' get_run_info("model/nonmem/run001/run001.lst")
#' model <- read_model("model/nonmem/run001.mod")
#' get_run_info(model)
#' }
get_run_info <- function(path) .Call(wrap__get_run_info, path)

#' Checks mod file for nmtran errors
#'
#' @param model_path path to nonmem model file, or a hyperion_nonmem_model object
#'
#' @return exit code of NMTRAN
#' @export
#'
#' @examples \dontrun{
#' check_model("model/nonmem/1001.mod")
#' model <- read_model("model/nonmem/1001.mod")
#' check_model(model)
#' }
check_model <- function(model_path) .Call(wrap__check_model_wrap, model_path)

#' Checks model dataset
#'
#' @param model hyperion_nonmem_model object from `read_model`
#'
#' @return Dataset check results
#' @export
check_dataset <- function(model) .Call(wrap__check_dataset, model)

#' Show model lineage and relationships.
#'
#' With no arguments, returns the full project lineage tree. Supplying a
#' model path returns that model's full lineage (ancestors and descendants).
#' The `from` and `to` arguments filter the tree from a model downward, up
#' to a model, or to the slice between two models. The project is always
#' rooted at the directory containing `pharos.toml`.
#'
#' @param model Optional `hyperion_nonmem_model` object or model file path.
#' Returns the model's full lineage (ancestors and descendants). Conflicts
#' with `from`/`to`.
#' @param from Filter the tree to this model and everything downstream.
#' Accepts a `hyperion_nonmem_model` object or a model file path.
#' @param to Filter the tree to this model and everything upstream.
#' Accepts a `hyperion_nonmem_model` object or a model file path.
#'
#' @return hyperion_nonmem_tree S3 object
#' @export
#'
#' @examples \dontrun{
#' get_model_lineage()                                            # whole project
#' get_model_lineage("model/nonmem/run003.mod")                   # full lineage of run003
#' get_model_lineage(from = "model/nonmem/run001.mod")            # run001 and descendants
#' get_model_lineage(to = "model/nonmem/run003.mod")              # run003 and ancestors
#' get_model_lineage(from = "model/nonmem/run001.mod",
#'                   to   = "model/nonmem/run003.mod")            # slice between two models
#' }
get_model_lineage <- function(model = NULL, from = NULL, to = NULL) .Call(wrap__get_model_lineage, model, from, to)

#' Gets parameter estimates from model run
#'
#' @param path path to model file, model output directory, ext file or metadata json file,
#' or a hyperion_nonmem_model object
#' @param hide_off_diagonal_params boolean, if TRUE will not display the unfixed off-diagonal
#' estimated parameters
#' @param only_method character, filter for getting estimates from specified method only.
#' Available methods are Fo, Foce, Saems, Bayes, Imp, ImpMap, Its, Nuts
#' @param only_last boolean, for grabbing only last estimation method parameters
#' @param show_table_idx boolean, if TRUE include table_idx column in output
#' @param show_method boolean, if TRUE include method column in output
#'
#' @return data.frame of parameter estimates
#' @export
#'
#' @examples \dontrun{
#' get_parameters("model/nonmem/run001/run001.ext")
#' model <- read_model("model/nonmem/run001.mod")
#' get_parameters(model)
#' }
get_parameters <- function(path, hide_off_diagonal_params = FALSE, only_method = NULL, only_last = TRUE, show_table_idx = FALSE, show_method = FALSE) .Call(wrap__get_parameters, path, hide_off_diagonal_params, only_method, only_last, show_table_idx, show_method)

#' Gets parameter names from model using typed comment parsing (internal)
#'
#' This function extracts parameter names using the pharos typed comment parser.
#' For general use, prefer the R-side get_parameter_names() which handles both
#' typed and raw comment formats.
#'
#' @param model hyperion_nonmem_model object from read_model()
#'
#' @return Named list with NONMEM names as names and user-friendly names as character values
#' @keywords internal
get_model_parameter_names <- function(model) .Call(wrap__get_model_parameter_names, model)

#' Build per-parameter comment info from a model object (internal)
#'
#' @param model hyperion_nonmem_model object from read_model()
#'
#' @return list with `thetas`, `omegas`, `sigmas` entries; each is a list of
#'   length-2 lists `(coordinate, info)` in numeric coordinate order.
#' @keywords internal
get_model_comment_info <- function(model) .Call(wrap__get_model_comment_info, model)

#' Canonicalize a parameterization alias to its PascalCase form.
#'
#' @param raw Parameterization alias (e.g. `"EXP"`, `"lognormal"`, `"PROP"`).
#' @return Canonical name (`"LogNormal"`, `"Proportional"`, ...) or `NA_character_`
#'   if `raw` is not a recognized alias.
#' @keywords internal
map_parameterization <- function(raw) .Call(wrap__map_parameterization, raw)

#' Creates a metadata file for a NONMEM model
#'
#' This function creates a metadata file that stores information about a NONMEM model,
#' including its description, tags, and lineage information. The metadata is stored
#' in a structured format that can be used for model tracking and documentation.
#'
#' @param model_path Path to the NONMEM model file, or a hyperion_nonmem_model object (required)
#' @param description Optional description of the model and its purpose
#' @param tags Character vector of tags to categorize or label the model
#' @param based_on Character vector of model names/paths that this model is based on
#' @param copied_from Optional model name/path this model was mechanically copied from
#'
#' @return Returns invisibly after creating the metadata file
#' @export
#'
#' @examples
#' \dontrun{
#' # Create basic metadata for a model
#' set_metadata_file("run001.mod", description = "Base population PK model")
#'
#' # Create metadata using a model object
#' model <- read_model("run001.mod")
#' set_metadata_file(model, description = "Base population PK model")
#'
#' # Create metadata with tags and lineage
#' set_metadata_file(
#'   "run002.mod",
#'   description = "PK model with covariate effects",
#'   tags = c("population", "pk", "covariates"),
#'   based_on = c("run001.mod")
#' )
#' }
set_metadata_file <- function(model_path, description = NULL, tags = NULL, based_on = NULL, copied_from = NULL) .Call(wrap__set_metadata_file, model_path, description, tags, based_on, copied_from)

#' Updates a metadatafile
#'
#' @param model_path path to model file or metadata file to update, or a hyperion_nonmem_model object
#' @param description Optional description to add to metadata
#' @param tags Optional character vector of tags to add to tags field
#' @param based_on character vector of models to add to based_on field
#'
#' @return Invisibly after updaing
#' @export
#'
#' @examples \dontrun{
#' update_metadata_file("model/nonmem/run001.mod", tags = "key model")
#' update_metadata_file("model/nonmem/run004.mod", tags = "key model", based_on = "1002")
#' model <- read_model("model/nonmem/run001.mod")
#' update_metadata_file(model, tags = "key model")
#' }
update_metadata_file <- function(model_path, description = NULL, tags = NULL, based_on = NULL) .Call(wrap__append_to_metadata_file, model_path, description, tags, based_on)

#' Get model metadata from metadata JSON file
#'
#' Loads metadata for a NONMEM model from the model's sibling
#' `<model_stem>_metadata.json` file.
#'
#' @param model A hyperion_nonmem_model object from `read_model()`
#'
#' @return hyperion_model_metadata object containing:
#' \itemize{
#'   \item description - Model description string
#'   \item tags - Character vector of metadata tags
#'   \item based_on - Character vector of parent model references
#' }
#' @export
#'
#' @examples \dontrun{
#' mod <- read_model("model/nonmem/run001.mod")
#' meta <- get_model_metadata(mod)
#' meta$description
#' meta$tags
#' meta$based_on
#' }
get_model_metadata <- function(model) .Call(wrap__load_model_metadata, model)

#' Clear fields in a model's metadata file
#'
#' Selectively clears the `based_on`, `copied_from`, and/or `tags` fields in
#' the metadata file associated with a model. Fields not selected are left
#' unchanged.
#'
#' @param model_path Path to the NONMEM model file, or a hyperion_nonmem_model object
#' @param based_on If TRUE, clear the based_on field. Default FALSE.
#' @param copied_from If TRUE, clear the copied_from field. Default FALSE.
#' @param tags If TRUE, clear the tags field. Default FALSE.
#'
#' @return Returns invisibly after updating the metadata file
#' @export
#'
#' @examples \dontrun{
#' clear_metadata_file("model/nonmem/run001.mod", tags = TRUE)
#' model <- read_model("model/nonmem/run001.mod")
#' clear_metadata_file(model, based_on = TRUE, copied_from = TRUE)
#' }
clear_metadata_file <- function(model_path, based_on = FALSE, copied_from = FALSE, tags = FALSE) .Call(wrap__clear_metadata_file_wrap, model_path, based_on, copied_from, tags)

#' Migrate pharos run start files to project-relative model paths
#'
#' Rewrites every `pharos_start.json` under the project root, replacing the
#' absolute `model_canonical_path` written by older pharos versions with a
#' `model_path` relative to the project root. Files already in the current
#' format are left untouched. `.git` and `rv` directories are skipped.
#'
#' @param base_path Project root the runs were originally recorded under.
#' Only needed when the recorded absolute paths fall outside the current
#' project root, for example runs executed from another user's home
#' directory.
#'
#' @return nothing
#' @export
#'
#' @examples \dontrun{
#' migrate_run_start_files()
#' migrate_run_start_files(base_path = "/data/user-homes/analyst1/project-root")
#' }
migrate_run_start_files <- function(base_path = NULL) .Call(wrap__migrate_run_start_files, base_path)

#' Determine run status for a model path, run directory, or model object.
#'
#' @param input A hyperion_nonmem_model object, run directory, or model path.
#' @return "run", "running", or "not_run"
#'
#' Accepts .mod/.ctl/.lst paths, run directories, or a hyperion_nonmem_model object.
get_run_status <- function(input) .Call(wrap__get_run_status, input)

#' Reads ext file
#'
#' @param path path to model file, model output directory, ext file or metadata json file.
#' @param line_prefixes character vector for lines to filter for
#' @param parameters_only bool if true removes ITERATION and OBJ column, default false
#' @param only_method character, filter for getting estimates from specified method only
#' @param only_last boolean, for grabbing only last estimation method parameters
#'
#' @return data.frame of ext file
#' @export
#'
#' @examples \dontrun{
#' read_ext_file("model/nonmem/run001/run001.ext")
#' }
read_ext_file <- function(path, line_prefixes = NULL, parameters_only = FALSE, only_method = NULL, only_last = TRUE) .Call(wrap__read_ext_file, path, line_prefixes, parameters_only, only_method, only_last)

#' Gets all final estimates from an ext file or vector of ext files
#'
#' @param paths path to directory containing ext files (including subdirectories), single ext file, or vector of ext file paths
#' @param parameters_only bool if true removes ITERATION and OBJ column, default false
#' @param only_method character, filter for getting estimates from specified method only
#' @param only_last boolean, for grabbing only last estimation method parameters
#'
#' @return data.frame of final estimates with model names
#' @export
#'
#' @examples \dontrun{
#' get_final_estimates("model/nonmem/")
#' get_final_estimates("bootstrap/")  # Searches subdirectories recursively
#' get_final_estimates(c("run001.ext", "run002.ext", "run003.ext"))
#' }
get_final_estimates <- function(paths, parameters_only = TRUE, only_method = NULL, only_last = TRUE) .Call(wrap__get_final_estimates, paths, parameters_only, only_method, only_last)

#' Gets gradients of pararmeters during modeling
#'
#' @param path path to model file, model output directory, grd file or metadata json file,
#' or a hyperion_nonmem_model object
#' @param only_method character, filter for getting estimates from specified method only.
#' Available methods are Fo, Foce, Saems, Bayes, Imp, ImpMap, Its, Nuts
#' @param only_last boolean, for grabbing only last estimation method parameters
#'
#' @return data.frame of gradients
#' @export
#'
#' @examples \dontrun{
#' get_gradients("model/nonmem/run001/run001.grd")
#' model <- read_model("model/nonmem/run001.mod")
#' get_gradients(model)
#' }
get_gradients <- function(path, only_method = NULL, only_last = TRUE) .Call(wrap__get_gradients, path, only_method, only_last)

#' Gets ETA shrinkage metrics from .shk file
#'
#' @param path path to model file, model output directory, shk file or metadata json file,
#' or a hyperion_nonmem_model object
#'
#' @return data.frame of ETA shrinkage metrics
#' @export
#'
#' @examples \dontrun{
#' get_eta_shrinkage("model/nonmem/run001/run001.shk")
#' model <- read_model("model/nonmem/run001.mod")
#' get_eta_shrinkage(model)
#' }
get_eta_shrinkage <- function(path) .Call(wrap__get_eta_shrinkage, path)

#' Gets EPS shrinkage metrics from .shk file
#'
#' @param path path to model file, model output directory, shk file or metadata json file,
#' or a hyperion_nonmem_model object
#'
#' @return data.frame of EPS shrinkage metrics
#' @export
#'
#' @examples \dontrun{
#' get_eps_shrinkage("model/nonmem/run001/run001.shk")
#' model <- read_model("model/nonmem/run001.mod")
#' get_eps_shrinkage(model)
#' }
get_eps_shrinkage <- function(path) .Call(wrap__get_eps_shrinkage, path)

#' Compute coefficient of variation (CV%) for random effect parameters
#'
#' Calculates the CV% for Omega/Sigma diagonal parameters based on the
#' specified transformation. For LogNormal and AddErr transforms, uses
#' `sqrt(exp(estimate) - 1) * 100`. For Proportional, uses `sqrt(estimate) * 100`.
#' Returns NA for Theta parameters or Identity transform as CV is not meaningful.
#'
#' @param estimate The parameter estimate(s) (variance scale), can be a vector
#' @param param_type Parameter type(s), can be a vector: "Theta", "Omega", or "Sigma"
#' @param transform Transformation type(s), can be a vector: "LogNormal", "AddErr", "Proportional", or "Identity". Defaults to "Identity".
#'
#' @return CV as a percentage (vector), or NA if not applicable
#' @export
#'
#' @examples \dontrun{
#' compute_cv(0.09, "Omega", "LogNormal")
#' df %>% mutate(cv = compute_cv(estimate, kind, "LogNormal"))
#' }
compute_cv <- function(estimate, param_type, transform = 'identity') .Call(wrap__compute_cv, estimate, param_type, transform)

#' Compute confidence interval for parameter estimates
#'
#' Calculates confidence intervals using the Wald method with optional
#' back-transformation. For LogNormal transform, the CI is computed on the
#' log scale and then exponentiated. For other transforms, standard
#' symmetric intervals are computed.
#'
#' @param estimate The parameter estimate(s), can be a vector
#' @param se The standard error(s) of the estimate(s), can be a vector
#' @param ci_level Confidence level between 0 and 1 (e.g., 0.95 for 95% CI). Defaults to 0.95.
#' @param transform Transformation type(s), can be a vector: "LogNormal", "AddErr", "Proportional", or "Identity". Defaults to "Identity".
#'
#' @return A list with `lower` and `upper` vectors for the CI bounds
#' @export
#'
#' @examples \dontrun{
#' compute_ci(1.5, 0.2)$lower
#' df %>% mutate(
#'   ci_lower = compute_ci(estimate, se)$lower,
#'   ci_upper = compute_ci(estimate, se)$upper
#' )
#' }
compute_ci <- function(estimate, se, ci_level = 0.95, transform = 'identity') .Call(wrap__compute_ci, estimate, se, ci_level, transform)

#' Compute relative standard error (RSE%) for parameter estimates
#'
#' Calculates the RSE% based on the specified transformation and parameter type.
#' For LogNormal Omega/Sigma, uses `sqrt(exp(se^2) - 1) * 100`.
#' For other transforms, uses `se / |estimate| * 100`.
#'
#' @param estimate The parameter estimate(s), can be a vector
#' @param se The standard error(s) of the estimate(s), can be a vector
#' @param param_type Parameter type(s), can be a vector: "Theta", "Omega", or "Sigma"
#' @param transform Transformation type(s), can be a vector: "LogNormal", "AddErr", "Proportional", or "Identity". Defaults to "Identity".
#'
#' @return RSE as a percentage (vector)
#' @export
#'
#' @examples \dontrun{
#' compute_rse(1.5, 0.2, "Theta")
#' df %>% mutate(rse = compute_rse(estimate, stderr, kind))
#' }
compute_rse <- function(estimate, se, param_type, transform = 'identity') .Call(wrap__compute_rse, estimate, se, param_type, transform)

#' Back-transform a parameter value to the natural scale
#'
#' Applies the inverse transformation to convert a parameter from the
#' estimation scale to the natural/interpretable scale. For LogNormal,
#' this exponentiates the value. For Identity, Proportional, and AddErr,
#' the value is returned unchanged.
#'
#' @param value The parameter value(s) on the estimation scale, can be a vector
#' @param transform Transformation type(s), can be a vector: "LogNormal", "AddErr", "Proportional", or "Identity"
#'
#' @return The back-transformed value(s) on the natural scale
#' @export
#'
#' @examples \dontrun{
#' transform_value(0.5, "LogNormal")
#' transform_value(c(0.5, 1.0), "LogNormal")
#' }
transform_value <- function(value, transform) .Call(wrap__transform_value, value, transform)

#' Gets the pharos.toml configuration as an R object
#'
#' @return pharos config as nested list structure
#' @export
#'
#' @examples \dontrun{
#' config <- get_pharos_config()
#' config$nonmem$summary$high_correlation_threshold
#' config$nonmem$summary$high_condition_threshold
#' }
get_pharos_config <- function() .Call(wrap__get_pharos_config)

#' Get the comment type from pharos.toml config file
#'
#'
#' @return CommentType R object
#' @export
#'
#' @examples \dontrun{
#' get_comment_type()
#' }
get_comment_type <- function() .Call(wrap__get_comment_type_wrap)

#' Validate and resolve a model path (.mod or .ctl).
#'
#' @keywords internal
#' @noRd
validate_model_path <- function(path) .Call(wrap__validate_model_path_wrap, path)

#' Convert a config-relative path to an absolute path.
#'
#' Resolves a path stored relative to the project configuration directory
#' (the directory containing `pharos.toml`) to an absolute path. If the
#' path is already absolute, it is returned unchanged.
#'
#' @details hyperion model objects store paths relative to the project
#' configuration directory. Use this function to resolve them to absolute
#' paths for file system operations.
#'
#' @param path A config-relative or absolute file path.
#' @return The absolute file path as a character string.
#' @export
from_config_relative <- function(path) .Call(wrap__from_config_relative_wrap, path)

#' Convert an absolute path to be relative to the pharos config directory.
#'
#' @param path Absolute path to make relative.
#' @return Path relative to pharos.toml directory, or original path if not under config dir.
#' @keywords internal
#' @noRd
to_config_relative <- function(path) .Call(wrap__to_config_relative_wrap, path)

#' Submits a NONMEM model to SLURM for execution
#'
#' This function submits a NONMEM model file to a SLURM cluster for execution,
#' allowing for parallel processing and job queue management. The function handles
#' job configuration, resource allocation, and job submission through pharos
#'
#' @param model A hyperion_nonmem_model object, path to the NONMEM model file,
#' or character vector of model paths/patterns (required)
#' @param overwrite Whether to overwrite existing output files (default: FALSE)
#' @param dry_run Whether to perform a dry run without actually submitting the job (default: FALSE)
#' @param run_in_output_dir Whether to run the job in the output directory (default: FALSE)
#' @param ncpu Number of CPUs to allocate for the job (default: 1)
#' @param partition SLURM partition to submit the job to (default: NULL, uses cluster default)
#' @param clean_level Level of cleanup to perform after job completion (default: 1)
#' @param parafile Path to parameter file for parallel runs (default: NULL)
#' @param template Path to SLURM template file for job submission (default: NULL)
#' @param account SLURM account to charge the job to (default: NULL)
#' @param verbose Whether to include DEBUG logs in output log file (default: FALSE)
#'
#' @return Returns invisibly after printing job submission results. Prints model path and corresponding SLURM job ID for each submitted job.
#' @export
#'
#' @examples
#' \dontrun{
#' # Submit a basic NONMEM model
#' submit_model_to_slurm("model.mod")
#'
#' # Submit using a model object
#' model <- read_model("model.mod")
#' submit_model_to_slurm(model)
#'
#' # Dry run to test submission without actually running
#' submit_model_to_slurm("model.mod", dry_run = TRUE)
#'
#' # Submit to specific partition with account
#' submit_model_to_slurm("model.mod", partition = "gpu", account = "myproject")
#' }
submit_model_to_slurm <- function(model, overwrite = FALSE, dry_run = FALSE, run_in_output_dir = FALSE, ncpu = 1, partition = NULL, clean_level = 1, parafile = NULL, template = NULL, account = NULL, verbose = FALSE) .Call(wrap__submit_model_to_slurm, model, overwrite, dry_run, run_in_output_dir, ncpu, partition, clean_level, parafile, template, account, verbose)

#' Submits a NONMEM model to SGE for execution
#'
#' This function submits a NONMEM model file to a SGE cluster for execution,
#' allowing for parallel processing and job queue management. The function handles
#' job configuration, resource allocation, and job submission through pharos
#'
#' @param model A hyperion_nonmem_model object, path to the NONMEM model file,
#' or character vector of model paths/patterns (required)
#' @param overwrite Whether to overwrite existing output files (default: FALSE)
#' @param dry_run Whether to perform a dry run without actually submitting the job (default: FALSE)
#' @param run_in_output_dir Whether to run the job in the output directory (default: FALSE)
#' @param ncpu Number of CPUs to allocate for the job (default: 1)
#' @param clean_level Level of cleanup to perform after job completion (default: 1)
#' @param parafile Path to parameter file for parallel runs (default: NULL)
#' @param template Path to SGE template file for job submission (default: NULL)
#' @param verbose Whether to include DEBUG logs in output log file (default: FALSE)
#'
#' @return Returns invisibly after printing job submission results. Prints model path and corresponding SGE job ID for each submitted job.
#' @export
#'
#' @examples
#' \dontrun{
#' # Submit a basic NONMEM model
#' submit_model_to_sge("model.mod")
#'
#' # Submit using a model object
#' model <- read_model("model.mod")
#' submit_model_to_sge(model)
#'
#' # Dry run to test submission without actually running
#' submit_model_to_sge("model.mod", dry_run = TRUE)
#'}
submit_model_to_sge <- function(model, overwrite = FALSE, dry_run = FALSE, run_in_output_dir = FALSE, ncpu = 1, clean_level = 1, parafile = NULL, template = NULL, verbose = FALSE) .Call(wrap__submit_model_to_sge, model, overwrite, dry_run, run_in_output_dir, ncpu, clean_level, parafile, template, verbose)

#' Get the cluster partition information
#'
#' @return Data frame of partition info
#' @export
#'
#' @examples \dontrun{
#' get_partition_info()
#' }
get_partition_info <- function() .Call(wrap__get_partition_info)

# nolint end
